# Por aqui começaremos a fazer o merge das tabelas para depois começarmos o EDA profundo

In [3]:
import pandas as pd
# Carrega o arquivo que você arrumou ontem
df_logistica = pd.read_csv('../data/logistica.csv')

# Carrega as outras tabelas do projeto 
df_pedidos = pd.read_csv('../data/pedidos.csv')
df_clientes = pd.read_csv('../data/clientes.csv')
df_itens = pd.read_csv('../data/itens_vendas.csv')

In [4]:
# Intens vendas é o coraçao do projeto
linhas_iniciais = df_itens.shape[0]
print(f"Linhas iniciais: {linhas_iniciais}")

Linhas iniciais: 11

In [7]:
# 1. Cruzamento inicial: Itens (coração) + Pedidos (capa do pedido)
# Estamos assumindo que a coluna que liga as duas se chama 'id_pedido'. 
# (Ajuste se o nome da coluna for diferente)
df_merge_1 = pd.merge(df_itens, df_pedidos, on='ID_Pedido', how='left')

# prova real imediata
linhas_apos_merge = df_merge_1.shape[0]
print(f"Linhas após juntar itens e pedidos: {linhas_apos_merge}")


# vendo se juntou as tabelas
display(df_merge_1.head())

Linhas após juntar itens e pedidos: 12

,ID_Item,ID_Pedido,ID_Produto,Quantidade,Preco_Unitario,Taxa_Desconto,ID_Cliente,Data_Pedido,Status_Pagamento,Canal_Venda
0,1,1001,15.0,2,115.50,0.05,901,2026-09-01,Aprovado,Loja Fisica
1,2,1001,12.0,1,150.00,0.00,901,2026-09-01,Aprovado,Loja Fisica
2,3,1002,22.0,1,45.00,NaN,902,2026-09-01,Pendente,App
3,4,1003,15.0,5000,115.50,0.00,901,02-09-2026,Aprovado,App
4,5,1004,8.0,-1,15.99,0.10,903,2026-09-02,Recusado,Site

# 3. Cruzamento: Base atual (Itens + Pedidos) + Clientes
# A chave que liga as duas tabelas agora é o 'ID_Cliente'

In [11]:
df_merge_2 = pd.merge(df_merge_1, df_clientes, on='ID_Cliente', how='left')
# Prova real
linhas_com_clientes =df_merge_2.shape[0]
print(f"Linhas após juntar clientes: {linhas_com_clientes}")

# Vendo o resultado (deve aparecer nome, estado, etc. lá no final das colunas)
display(df_merge_2.head())

Linhas após juntar clientes: 12

,ID_Item,ID_Pedido,ID_Produto,Quantidade,Preco_Unitario,Taxa_Desconto,ID_Cliente,Data_Pedido,Status_Pagamento,Canal_Venda,Nome,Idade,Estado,Email,Data_Cadastro
0,1,1001,15.0,2,115.50,0.05,901,2026-09-01,Aprovado,Loja Fisica,Vitor Ferrari,22.0,SP,vitor.f@email.com,2025-11-10
1,2,1001,12.0,1,150.00,0.00,901,2026-09-01,Aprovado,Loja Fisica,Vitor Ferrari,22.0,SP,vitor.f@email.com,2025-11-10
2,3,1002,22.0,1,45.00,NaN,902,2026-09-01,Pendente,App,Ana Souza,150.0,São Paulo,ana.souza@email.com,2026-01-15
3,4,1003,15.0,5000,115.50,0.00,901,02-09-2026,Aprovado,App,Vitor Ferrari,22.0,SP,vitor.f@email.com,2025-11-10
4,5,1004,8.0,-1,15.99,0.10,903,2026-09-02,Recusado,Site,Carlos Silva,NaN,RJ,carlos.silva.com,2026-02-20

In [12]:
# 4. Último Merge: Base atual (Itens + Pedidos + Clientes) + Logística
# Ajuste o 'on' se a coluna chave na tabela de logística tiver um nome diferente (ex: id_pedido minúsculo)
df_final = pd.merge(df_merge_2, df_logistica, on='ID_Pedido', how='left')

# Checagem de segurança (tem que manter as 11 linhas iniciais)
print(f"Linhas do Dataset Master: {df_final.shape[0]}")

# Salva o arquivo final consolidado para usar no próximo passo
df_final.to_csv('../data/dataset_consolidado.csv', index=False)

display(df_final.head())

Linhas do Dataset Master: 12

,ID_Item,ID_Pedido,ID_Produto,Quantidade,Preco_Unitario,Taxa_Desconto,ID_Cliente,Data_Pedido,Status_Pagamento,Canal_Venda,Nome,Idade,Estado,Email,Data_Cadastro,ID_Entrega,Status_Entrega,Tempo_Entrega_Dias,Regiao,Custo_Frete
0,1,1001,15.0,2,115.50,0.05,901,2026-09-01,Aprovado,Loja Fisica,Vitor Ferrari,22.0,SP,vitor.f@email.com,2025-11-10,501,Entregue,2.0,Sudeste,15.5
1,2,1001,12.0,1,150.00,0.00,901,2026-09-01,Aprovado,Loja Fisica,Vitor Ferrari,22.0,SP,vitor.f@email.com,2025-11-10,501,Entregue,2.0,Sudeste,15.5
2,3,1002,22.0,1,45.00,NaN,902,2026-09-01,Pendente,App,Ana Souza,150.0,São Paulo,ana.souza@email.com,2026-01-15,502,Em Rota,1.0,Sudeste,12.0
3,4,1003,15.0,5000,115.50,0.00,901,02-09-2026,Aprovado,App,Vitor Ferrari,22.0,SP,vitor.f@email.com,2025-11-10,503,Entregue,0.0,Sudeste,0.0
4,5,1004,8.0,-1,15.99,0.10,903,2026-09-02,Recusado,Site,Carlos Silva,NaN,RJ,carlos.silva.com,2026-02-20,504,Devolvido,5.0,Sudeste,25.0